### ISSUE TITLE
dst_grid_dims and src_grid_dims in TempestRemap files

### ISSUE THREAD

**Issue by mt5555** [czender/nco#11]
TempestRemap recently (2015-8-14) tweaked it's map file format to be more compatible with SCRIP.  In particular, dst_grid_dims() and src_grid_dims() are now in lon/lat order.   This has the advantage that TempestRemap mapping files can now be applied by ESMF based utilities.  But it breaks ncks.  

To get ncks to work with this new version, I made the following change (listed below for reference - I realize this is not a good way to fix this). 

diff --git a/src/nco/nco_rgr.c b/src/nco/nco_rgr.c
index a4b1204..da18ba6 100644
--- a/src/nco/nco_rgr.c
+++ b/src/nco/nco_rgr.c
@@ -716,8 +716,8 @@ nco_rgr_map /* [fnc] Regrid with external weights */
   int lat_psn_dst=int_CEWI; /* [idx] Ordinal position of latitude  size in rectangular destination
   if(flg_grd_in_2D){
     if(nco_rgr_mpf_typ == nco_rgr_mpf_Tempest){
-      lon_psn_src=1;
-      lat_psn_src=0;
+      lon_psn_src=0;
+      lat_psn_src=1;
     }else{
       lon_psn_src=0;
       lat_psn_src=1;
@@ -725,8 +725,8 @@ nco_rgr_map /* [fnc] Regrid with external weights */
   } /* !flg_grd_in_2D */
   if(flg_grd_out_2D){
     if(nco_rgr_mpf_typ == nco_rgr_mpf_Tempest){
-      lon_psn_dst=1;
-      lat_psn_dst=0;
+      lon_psn_dst=0;
+      lat_psn_dst=1;
     }else{
       lon_psn_dst=0;
       lat_psn_dst=1;

**Comment by czender** [comment]
Thanks, Mark. Glad this works for now. I thought I had it coded to work when Tempest made the switch but I overlooked this clause. The final patch has to ensure that old Tempest mapping files do not break. I think that's mostly coded though. Will include all this in 4.5.2-final soon.

**Comment by czender** [comment]
NCO now patched to work with older and newer Tempest lon/lat orders. The patch relies on contents of "name0" attribute of src/dst_grid_dims to indicate when the old ordering should be followed. Otherwise ncks assumes the newer ordering. Are there even older Tempest mapfiles that do not have the "name0" attribute? If so NCO will break on those, but otherwise looks good for all recent versions of Tempest. Patch included in 4.5.2-alpha9.
