### ISSUE TITLE
ncks segfault with --rgr grid* options

### ISSUE THREAD

**Issue by mt5555** [czender/nco#12]
This command

ncks  -O -D 10 --rgr grd_ttl='FV-scalar grid' \
  --rgr grid=/tmp/65x128_SCRIP.nc --rgr lat_nbr=65 \
  --rgr lon_nbr=128 --rgr lat_typ=ngl_eqi_pol --rgr lon_typ=Grn_ctr \
  ~/codes/nco/data/in.nc /tmp/foo.nc

will produce a grid file that appears correct, but then will exit with a segfault:

On RHEL6: 

...
ncks: INFO nco_grd_mk() reports destination rectangular latitude grid:
lat_wgt_ttl =    2.000000000000000, frc_lat_wgt =    1.000000000000000, area_ttl =   12.566370614358775, frc_area =    0.999999999999968
ncks: nco_fl_out_open() reports sizeof(pid_t) = 4 bytes, pid = 9468, pid_sng_lng = 5 bytes, strlen(pid_sng) = 4 bytes, fl_out_tmp_lng = 38 bytes, strlen(fl_out_tmp) = 37, fl_out_tmp = /tmp/65x128_SCRIP.nc.pid9468.ncks.tmp
ncks: INFO nco_aed_prc() examining variable Global
ncks: INFO nco_aed_prc() examining variable Global
ncks: INFO nco_aed_prc() examining variable Global
ncks: INFO nco_aed_prc() examining variable Global
ncks: INFO nco_aed_prc() examining variable Global
ncks: INFO nco_aed_prc() examining variable area
ncks: INFO nco_aed_prc() examining variable grid_center_lat
ncks: INFO nco_aed_prc() examining variable grid_center_lon
ncks: INFO nco_aed_prc() examining variable grid_corner_lat
ncks: INFO nco_aed_prc() examining variable grid_corner_lon
ncks: INFO Temporary and final files /tmp/65x128_SCRIP.nc are identical---no need to move.
Segmentation fault

**Comment by mt5555** [comment]
On OSX, a little bit more information:  

...
ncks: INFO Temporary and final files /tmp/65x128_SCRIP.nc are identical---no need to move.
ncks(21145,0x7fff7c7e2300) malloc: *** error for object 0x7ffd8a0195d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort

**Comment by czender** [comment]
Thanks, problem found, fixed, and pushed. Please update. re-try, and re-open if it doesn't work for you.

**Comment by mt5555** [comment]
resolved, thanks.
