### ISSUE TITLE
Version number mismatch

### ISSUE THREAD

**Issue by serbinsh** [czender/nco#2]
Hello
Not a major bug, and may not be a bug at all, but I just compiled version (release) 4.4.8 from git on my machine and when I check the installed version number on the bin files I get this:

NCO netCDF Operators version 4.4.9 built by sserbin on test at Feb 28 2015 12:08:17
ncap2 version "4.4.9"

However the version number downloaded was indicated as 4.4.8.  I am running on SciLinux 6.5 with the latest version of netCDF (4.3.3.1).

Shawn

**Comment by czender** [comment]
Thanks for reporting this, Shawn. I'll try to finalize the NCO githug tag/release system next week. Still figuring out how I want it to work. Rest assured that what you have is functionally equivalent to 4.4.8. cz

**Comment by serbinsh** [comment]
Got it, thanks!

**Comment by czender** [comment]
Master branch now differs in features from 4.4.8 so i'll try to fix the tagging this week...

**Comment by czender** [comment]
I'm homing in on a not terrible release procedure. Ended up deleting the mislabeled 4.4.8 release that started this all.
